[project]
name = "llm-pet"
version = "0.1.0"
description = "Pet project for learning LLMs"
authors = [
    {name = "Tom Ferdinandt",email = "tomfs@icloud.com"}
]
requires-python = "~=3.12"
# darwin is for macOS (much lower versions, to get linter to work on my intel machine)
# linux is for google colab, and uses the actually up to date versions
dependencies = [
    "torch~=2.2.2 ; sys_platform == 'darwin'",
    "torch>=2.2.2 ; sys_platform == 'linux'",
    "requests (>=2.34.2,<3.0.0) ; sys_platform == 'darwin'",
    "requests>=2.34.2 ; sys_platform == 'linux'",
    "numpy (>=1.26.4,<2.0.0) ; sys_platform == 'darwin'",
    "numpy>=1.26.4 ; sys_platform == 'linux'",
    "tqdm (>=4.67.3,<5.0.0) ; sys_platform == 'darwin'",
    "tqdm>=4.67.3 ; sys_platform == 'linux'",
    "lightning (>=2.6.5,<3.0.0) ; sys_platform == 'darwin'",
    "lightning>=2.6.5 ; sys_platform == 'linux'",
    "pandas[parquet] (<3.0.0) ; sys_platform == 'darwin'",
    "pandas[parquet]>=2.2.0 ; sys_platform == 'linux'"
]

[dependency-groups]
dev = [
    "ruff (>=0.15.15,<0.16.0)",
    "jupyter (>=1.1.1,<2.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
